# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('publish_date', models.DateField(default=datetime.datetime(2016, 12, 27, 13, 30, 15, 12000, tzinfo=utc))),
                ('description', models.TextField()),
            ],
        ),
    ]
