# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 14:59
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(default=b'adres-url'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 27, 14, 59, 12, 825000, tzinfo=utc)),
        ),
    ]
