# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 15:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betservice', '0002_auto_20161227_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2016, 12, 27, 15, 11, 14, 374000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
