# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 19:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('betservice', '0004_auto_20161229_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ateam', models.CharField(max_length=200)),
                ('bteam', models.CharField(max_length=200)),
                ('score1', models.CharField(max_length=10)),
                ('score2', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.datetime(2017, 1, 23, 19, 10, 40, 335000, tzinfo=utc))),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 23, 19, 10, 40, 319000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 23, 19, 10, 40, 319000, tzinfo=utc)),
        ),
    ]
