# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betservice', '0005_auto_20170123_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='ateam',
            new_name='team1',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='bteam',
            new_name='team2',
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 23, 19, 21, 16, 191000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bet',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 23, 19, 21, 16, 191000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 23, 19, 21, 16, 191000, tzinfo=utc)),
        ),
    ]
