# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 21:50
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betservice', '0008_auto_20170123_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='bet',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 23, 21, 50, 54, 487000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bet',
            name='created',
            field=models.DateField(default=datetime.datetime(2017, 1, 23, 21, 50, 54, 490000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bet',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 23, 21, 50, 54, 490000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 23, 21, 50, 54, 488000, tzinfo=utc)),
        ),
    ]
