# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 21:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betservice', '0013_auto_20170123_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 24, 21, 25, 34, 4000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bet',
            name='created',
            field=models.DateField(default=datetime.datetime(2017, 1, 24, 21, 25, 34, 8000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bet',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 1, 24, 21, 25, 34, 7000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bet',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=b'0,00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bet',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=b'0,00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2017, 1, 24, 21, 25, 34, 6000, tzinfo=utc)),
        ),
    ]
